insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Jeep', 'Green', 'Serco', '2021-09-10T14:39:07Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Toyota', 'Yellow', 'McDonalds', '2021-07-17T16:56:09Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Land Rover', 'Pink', 'G4S', '2021-06-26T03:46:39Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Maroon', 'Serco', '2021-07-29T05:20:05Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Maserati', 'Violet', 'Timpsons', '2020-10-03T17:30:00Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mitsubishi', 'Aquamarine', 'Amazon', '2021-07-22T19:55:24Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('BMW', 'Yellow', 'ASDA', '2021-09-29T14:38:06Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Audi', 'Blue', 'G4S', '2021-08-15T01:41:30Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lamborghini', 'Indigo', 'McDonalds', '2021-09-08T12:56:20Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Toyota', 'Aquamarine', 'ACME Ltd', '2021-03-06T18:53:29Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Subaru', 'Purple', 'Google', '2021-05-17T06:53:55Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Maroon', 'G4S', '2020-09-24T00:16:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Yellow', 'Tesco', '2021-04-26T10:56:30Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Indigo', 'ASDA', '2020-10-06T10:06:18Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercury', 'Red', 'Amazon', '2021-03-25T22:02:13Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Honda', 'Maroon', 'Nestle', '2021-04-30T02:49:52Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Chevrolet', 'Blue', 'Timpsons', '2021-09-06T07:49:00Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Cadillac', 'Yellow', 'McDonalds', '2021-05-12T15:54:02Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercury', 'Blue', 'ASDA', '2021-04-19T19:58:27Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Purple', 'McDonalds', '2021-09-28T20:25:05Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Hyundai', 'Mauv', 'Google', '2021-02-08T02:34:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Nissan', 'Red', 'P&G', '2021-07-25T16:42:02Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Nissan', 'Pink', 'P&G', '2021-04-17T06:30:47Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('BMW', 'Indigo', 'Amazon', '2021-04-09T22:53:01Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Geo', 'Khaki', 'ACME Ltd', '2021-01-21T15:59:42Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Hyundai', 'Turquoise', 'G4S', '2021-07-19T20:16:18Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Scion', 'Yellow', 'G4S', '2021-08-11T13:19:56Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Violet', 'Amazon', '2020-12-24T00:37:27Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lamborghini', 'Orange', 'McDonalds', '2021-03-17T17:34:29Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Pink', 'Amazon', '2021-09-10T02:50:50Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('GMC', 'Maroon', 'McDonalds', '2020-11-11T02:28:18Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Khaki', 'Google', '2021-03-11T10:31:47Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Porsche', 'Goldenrod', 'Nestle', '2020-09-27T18:48:07Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Chrysler', 'Teal', 'Timpsons', '2021-02-27T18:12:39Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lexus', 'Teal', 'Nestle', '2021-02-19T23:53:07Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('GMC', 'Goldenrod', 'ACME Ltd', '2021-09-07T17:50:09Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Chevrolet', 'Red', 'Timpsons', '2021-08-07T11:30:53Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Pink', 'Amazon', '2020-11-15T00:30:32Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Cadillac', 'Yellow', 'ASDA', '2021-01-21T05:07:00Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Puce', 'ACME Ltd', '2021-01-22T23:04:53Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Subaru', 'Red', 'G4S', '2021-03-17T05:43:11Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mazda', 'Maroon', 'ASDA', '2021-07-15T22:58:05Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Volkswagen', 'Yellow', 'Tesco', '2020-12-05T15:04:55Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Dodge', 'Puce', 'Amazon', '2020-09-29T19:19:17Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lincoln', 'Violet', 'G4S', '2021-05-10T04:37:40Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Aquamarine', 'ACME Ltd', '2021-05-29T02:32:12Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Dodge', 'Pink', 'LEGO', '2020-10-04T14:51:27Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Aquamarine', 'P&G', '2020-12-24T20:26:23Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('BMW', 'Blue', 'ASDA', '2021-09-02T12:40:09Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Nissan', 'Turquoise', 'ACME Ltd', '2020-11-26T17:02:16Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Buick', 'Green', 'Nestle', '2021-06-09T18:06:14Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Subaru', 'Teal', 'G4S', '2021-07-29T03:30:23Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Buick', 'Violet', 'ASDA', '2021-06-19T02:47:19Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('BMW', 'Blue', 'Google', '2020-11-30T09:47:35Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Acura', 'Pink', 'ACME Ltd', '2021-02-01T03:58:46Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Jeep', 'Crimson', 'Google', '2021-01-07T23:52:36Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('BMW', 'Green', 'Serco', '2020-12-11T02:21:39Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lotus', 'Green', 'ACME Ltd', '2021-01-13T20:04:19Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Ford', 'Purple', 'ASDA', '2021-09-10T17:38:54Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Dodge', 'Indigo', 'Serco', '2021-01-31T09:17:32Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Eagle', 'Crimson', 'G4S', '2020-11-26T07:12:05Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lincoln', 'Green', 'Timpsons', '2021-02-10T00:18:31Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Dodge', 'Aquamarine', 'ACME Ltd', '2021-01-17T12:03:35Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Oldsmobile', 'Khaki', 'LEGO', '2021-03-21T03:16:41Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('GMC', 'Purple', 'Nestle', '2021-06-11T11:51:20Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mitsubishi', 'Turquoise', 'LEGO', '2021-02-15T16:14:07Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Toyota', 'Mauv', 'LEGO', '2021-09-14T13:25:51Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Nissan', 'Goldenrod', 'Serco', '2020-09-28T04:37:05Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Acura', 'Teal', 'ACME Ltd', '2020-11-10T08:35:26Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Toyota', 'Mauv', 'P&G', '2021-09-23T09:30:16Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Acura', 'Violet', 'Timpsons', '2021-01-05T10:05:14Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Toyota', 'Green', 'LEGO', '2021-02-01T05:43:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Jaguar', 'Purple', 'Google', '2021-07-24T12:56:21Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Infiniti', 'Crimson', 'LEGO', '2021-08-18T20:43:57Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Aquamarine', 'Timpsons', '2021-04-25T20:25:10Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Green', 'Google', '2021-05-05T04:53:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Suzuki', 'Maroon', 'Nestle', '2021-04-25T07:07:12Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Isuzu', 'Pink', 'McDonalds', '2021-05-21T08:04:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Volvo', 'Red', 'Serco', '2021-05-10T01:02:53Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Turquoise', 'McDonalds', '2020-10-13T00:26:22Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('GMC', 'Purple', 'Nestle', '2021-06-11T23:50:59Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Subaru', 'Crimson', 'ASDA', '2020-09-24T22:55:27Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Hyundai', 'Yellow', 'P&G', '2021-05-13T18:53:25Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Khaki', 'G4S', '2020-11-15T01:58:28Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Lincoln', 'Puce', 'ACME Ltd', '2021-03-27T16:19:23Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Pink', 'ASDA', '2021-09-02T23:36:42Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Cadillac', 'Mauv', 'McDonalds', '2021-08-19T22:02:29Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Isuzu', 'Teal', 'McDonalds', '2021-04-21T02:50:50Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Scion', 'Puce', 'Serco', '2021-04-11T18:03:12Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercury', 'Aquamarine', 'Nestle', '2021-01-12T15:10:41Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Chevrolet', 'Yellow', 'Nestle', '2020-10-07T23:51:41Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Bentley', 'Khaki', 'G4S', '2021-05-08T06:26:06Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Mauv', 'Serco', '2021-08-05T06:03:02Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Hyundai', 'Goldenrod', 'P&G', '2021-04-18T22:10:40Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Cadillac', 'Aquamarine', 'Google', '2021-08-29T16:02:29Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Pontiac', 'Maroon', 'ACME Ltd', '2021-07-04T12:18:03Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Mercedes-Benz', 'Blue', 'Nestle', '2021-09-16T14:27:38Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Chevrolet', 'Puce', 'Tesco', '2020-11-09T06:20:37Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Eagle', 'Crimson', 'McDonalds', '2020-11-21T03:11:24Z');
insert into [VehicleDB].[dbo].[Vehicles] (Brand, Colour, BookedBy, BookingDate) values ('Suzuki', 'Fuscia', 'Google', '2021-03-21T13:20:25Z');
